version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-container
    restart: always
    env_file:
      - .env
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
volumes:
  mongodb-data: